<?php

namespace DataProcessingProjectBundle\Repository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends \Doctrine\ORM\EntityRepository
{

	public function findAllActivitiesForACategory( $category ){
		 $qb = $this->createQueryBuilder('a')
					->leftJoin('a.categories', 'cat')
    				->addSelect('cat')
    				;

    	return $qb->getQuery()->getResult()

  ;
	}
}
