<?php

namespace DataProcessingProjectBundle\Repository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{

	public function getApplicationsWithAdvert( $limit ){

		$qb = $this->createQueryBuilder( 'c' );

		$qb
			->join( 'c.advert', 'a' )
			->addSelect( 'a' )
		;

		$qb->setMaxResults( $limit );
		
		return $qb
			->getQuery()
			->getResult()
			;
	}
}
